CREATE TABLE "debris_objects" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"launch_year" integer,
	"launch_country" text,
	"jurisdiction" text,
	"mass_kg" real NOT NULL,
	"cross_section_m2" real NOT NULL,
	"intact" boolean DEFAULT false NOT NULL,
	"material_class" text,
	"altitude_km" real NOT NULL,
	"inclination_deg" real NOT NULL,
	"eccentricity" real DEFAULT 0 NOT NULL,
	"estimated_years_to_decay" real,
	"mission_status" text,
	"end_of_life_year" integer,
	"has_propellant" boolean DEFAULT false NOT NULL,
	"has_thrusters" boolean DEFAULT false NOT NULL,
	"conjunctions_30d" integer DEFAULT 0 NOT NULL,
	"neighbors_within_50km" integer DEFAULT 0 NOT NULL,
	"delta_v_to_reach_kms" real,
	"catalog_source" text DEFAULT 'simulated' NOT NULL,
	"last_updated" timestamp DEFAULT now()
);
